-- STUDENT LOGIN TABLE
CREATE TABLE students (
  id INT PRIMARY KEY,
  roll_number VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'student'
);

-- ADMIN LOGIN TABLE
CREATE TABLE admins (
  id INT PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  department VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin'
);
